#!/bin/env bash

hour=0
minute=1

while [ "$hour" -le 12 ]; do
  while [ "$minute" -le 59 ]; do
    printf "%02d:%02d\n" $hour $minute
    ((minute++))
  done
  ((hour++))
  minute=1
done | head -n 70
