#!/usr/bin/env bash
# This script configures an ubuntu server with the requirements below:
# -localhost resolves to 127.0.0.2
# -facebook.com resolves to 8.8.8.8

if [ "$EUID" -ne 0 ]; then
	  echo "This script must be run as root."
	    exit 1
fi

localhost_mapping="127.0.0.2 localhost"
facebook_mapping="8.8.8.8 facebook.com"

echo "$localhost_mapping" >> /etc/hosts
echo "$facebook_mapping" >> /etc/hosts

echo "Configuration complete. Hostname mappings updated:"
cat /etc/hosts
