#!/usr/bin/env bash
# This script configures an ubuntu server with the requirements below:
# -localhost resolves to 127.0.0.2
# -facebook.com resolves to 8.8.8.8

facebook='8.8.8.8 facebook.com'
hosts=/etc/hosts
cp $hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "$facebook" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
