#!/usr/bin/env bash
# This scipt displays all active IPV4 IPs on the machine it's executed on.

ipv4_addresses=$(ip -4 addr | grep -oP '(?<=inet\s)\d+(\.\d+){3}')

for ip in $ipv4_addresses; do
	echo "$ip"
done

